# Generated by Django 5.1.5 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, default=7000, max_digits=9),
        ),
    ]
