# Generated by Django 5.1.5 on 2025-05-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20250531_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_price',
        ),
    ]
